// <auto-generated />
using System;
using CylindricalPipeHeatLoss.API.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CylindricalPipeHeatLoss.API.Migrations
{
    [DbContext(typeof(HeatLossDbContext))]
    [Migration("20240511160324_ReportDB_ExtraFieldsRemoved")]
    partial class ReportDB_ExtraFieldsRemoved
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("CylindricalPipeHeatLoss.API.Models.DBModels.MaterialDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ACoeff")
                        .HasColumnType("REAL");

                    b.Property<double>("BCoeff")
                        .HasColumnType("REAL");

                    b.Property<double>("CCoeff")
                        .HasColumnType("REAL");

                    b.Property<int>("MaterialGroupID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)");

                    b.HasKey("ID");

                    b.HasIndex("MaterialGroupID");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ACoeff = -8.9999999999999995E-09,
                            BCoeff = 0.00037199999999999999,
                            CCoeff = 0.97399999999999998,
                            MaterialGroupID = 1,
                            Name = "ША"
                        },
                        new
                        {
                            ID = 2,
                            ACoeff = 0.0,
                            BCoeff = 0.00059000000000000003,
                            CCoeff = 0.80400000000000005,
                            MaterialGroupID = 1,
                            Name = "ШБ"
                        },
                        new
                        {
                            ID = 3,
                            ACoeff = 0.0,
                            BCoeff = 0.00035,
                            CCoeff = 0.46999999999999997,
                            MaterialGroupID = 2,
                            Name = "ШЛ-1,3"
                        },
                        new
                        {
                            ID = 4,
                            ACoeff = 0.0,
                            BCoeff = 0.00034699999999999998,
                            CCoeff = 0.48999999999999999,
                            MaterialGroupID = 2,
                            Name = "ШКЛ-1,3"
                        },
                        new
                        {
                            ID = 5,
                            ACoeff = 0.0,
                            BCoeff = 0.00035100000000000002,
                            CCoeff = 0.34999999999999998,
                            MaterialGroupID = 2,
                            Name = "ШЛ-1,0"
                        },
                        new
                        {
                            ID = 6,
                            ACoeff = -8.9999999999999995E-09,
                            BCoeff = 0.00023800000000000001,
                            CCoeff = 0.46999999999999997,
                            MaterialGroupID = 2,
                            Name = "ШЛА-1,3"
                        },
                        new
                        {
                            ID = 7,
                            ACoeff = -2.7E-08,
                            BCoeff = 0.00022699999999999999,
                            CCoeff = 0.307,
                            MaterialGroupID = 2,
                            Name = "ШЛА-1,0"
                        },
                        new
                        {
                            ID = 8,
                            ACoeff = -8.9999999999999995E-09,
                            BCoeff = 0.000205,
                            CCoeff = 0.316,
                            MaterialGroupID = 2,
                            Name = "ШЛ-0,9"
                        },
                        new
                        {
                            ID = 9,
                            ACoeff = -4.4999999999999999E-08,
                            BCoeff = 0.000176,
                            CCoeff = 0.20599999999999999,
                            MaterialGroupID = 2,
                            Name = "ШЛ-0,6"
                        },
                        new
                        {
                            ID = 10,
                            ACoeff = -1.7999999999999999E-08,
                            BCoeff = 0.000192,
                            CCoeff = 0.11899999999999999,
                            MaterialGroupID = 2,
                            Name = "ШЛ-0,4"
                        },
                        new
                        {
                            ID = 11,
                            ACoeff = 1.452E-06,
                            BCoeff = -0.004398,
                            CCoeff = 6.04,
                            MaterialGroupID = 3,
                            Name = "К"
                        },
                        new
                        {
                            ID = 13,
                            ACoeff = 9.9999999999999995E-08,
                            BCoeff = -0.00025900000000000001,
                            CCoeff = 0.89700000000000002,
                            MaterialGroupID = 4,
                            Name = "КЛ-1,3"
                        },
                        new
                        {
                            ID = 14,
                            ACoeff = 2.2000000000000001E-06,
                            BCoeff = -0.0061000000000000004,
                            CCoeff = 6.8399999999999999,
                            MaterialGroupID = 5,
                            Name = "МО-91"
                        },
                        new
                        {
                            ID = 15,
                            ACoeff = 2.12E-06,
                            BCoeff = -0.0058999999999999999,
                            CCoeff = 6.6100000000000003,
                            MaterialGroupID = 5,
                            Name = "М-3"
                        },
                        new
                        {
                            ID = 16,
                            ACoeff = 4.3699999999999997E-06,
                            BCoeff = -0.0124,
                            CCoeff = 12.1,
                            MaterialGroupID = 5,
                            Name = "МУ-89"
                        },
                        new
                        {
                            ID = 17,
                            ACoeff = 5.0200000000000002E-06,
                            BCoeff = -0.010999999999999999,
                            CCoeff = 10.6,
                            MaterialGroupID = 5,
                            Name = "М-4"
                        },
                        new
                        {
                            ID = 18,
                            ACoeff = 4.4800000000000003E-06,
                            BCoeff = -0.011299999999999999,
                            CCoeff = 12.1,
                            MaterialGroupID = 5,
                            Name = "М-6"
                        },
                        new
                        {
                            ID = 19,
                            ACoeff = 4.4000000000000002E-06,
                            BCoeff = -0.0117,
                            CCoeff = 12.199999999999999,
                            MaterialGroupID = 5,
                            Name = "М-7"
                        },
                        new
                        {
                            ID = 20,
                            ACoeff = 4.4000000000000002E-06,
                            BCoeff = -0.0117,
                            CCoeff = 12.1,
                            MaterialGroupID = 5,
                            Name = "М-8"
                        },
                        new
                        {
                            ID = 21,
                            ACoeff = 4.5000000000000001E-06,
                            BCoeff = -0.0118,
                            CCoeff = 12.0,
                            MaterialGroupID = 5,
                            Name = "М-9"
                        },
                        new
                        {
                            ID = 22,
                            ACoeff = 5.5899999999999998E-06,
                            BCoeff = -0.0149,
                            CCoeff = 14.0,
                            MaterialGroupID = 5,
                            Name = "МУ-91"
                        },
                        new
                        {
                            ID = 23,
                            ACoeff = 4.9599999999999999E-06,
                            BCoeff = -0.014800000000000001,
                            CCoeff = 14.4,
                            MaterialGroupID = 5,
                            Name = "МУ-92"
                        },
                        new
                        {
                            ID = 24,
                            ACoeff = 2.2000000000000001E-06,
                            BCoeff = -0.0061000000000000004,
                            CCoeff = 6.8399999999999999,
                            MaterialGroupID = 5,
                            Name = "МО-89"
                        },
                        new
                        {
                            ID = 25,
                            ACoeff = 4.4100000000000001E-06,
                            BCoeff = -0.0118,
                            CCoeff = 12.0,
                            MaterialGroupID = 5,
                            Name = "МГ"
                        },
                        new
                        {
                            ID = 26,
                            ACoeff = 2.3999999999999998E-07,
                            BCoeff = -0.00131,
                            CCoeff = 4.25,
                            MaterialGroupID = 6,
                            Name = "ПХСП"
                        },
                        new
                        {
                            ID = 27,
                            ACoeff = 9.7999999999999993E-07,
                            BCoeff = -0.0033300000000000001,
                            CCoeff = 4.7699999999999996,
                            MaterialGroupID = 6,
                            Name = "ПХСУТ"
                        },
                        new
                        {
                            ID = 28,
                            ACoeff = 9.7000000000000003E-07,
                            BCoeff = -0.00331,
                            CCoeff = 4.7199999999999998,
                            MaterialGroupID = 6,
                            Name = "ПХСУ"
                        },
                        new
                        {
                            ID = 29,
                            ACoeff = 3.7E-07,
                            BCoeff = -0.00089999999999999998,
                            CCoeff = 2.8199999999999998,
                            MaterialGroupID = 6,
                            Name = "ПХСОТ"
                        },
                        new
                        {
                            ID = 30,
                            ACoeff = 4.0999999999999999E-07,
                            BCoeff = -0.00091,
                            CCoeff = 2.98,
                            MaterialGroupID = 6,
                            Name = "ПХСС"
                        },
                        new
                        {
                            ID = 31,
                            ACoeff = 4.3000000000000001E-07,
                            BCoeff = -0.00115,
                            CCoeff = 2.6800000000000002,
                            MaterialGroupID = 7,
                            Name = "ХМ1-1"
                        },
                        new
                        {
                            ID = 32,
                            ACoeff = 4.2E-07,
                            BCoeff = -0.0011100000000000001,
                            CCoeff = 2.6600000000000001,
                            MaterialGroupID = 7,
                            Name = "ХМ2-1"
                        },
                        new
                        {
                            ID = 33,
                            ACoeff = 4.2E-07,
                            BCoeff = -0.0011000000000000001,
                            CCoeff = 2.6400000000000001,
                            MaterialGroupID = 7,
                            Name = "ХМ3-1"
                        },
                        new
                        {
                            ID = 34,
                            ACoeff = 3.7E-07,
                            BCoeff = -0.00101,
                            CCoeff = 2.3599999999999999,
                            MaterialGroupID = 7,
                            Name = "ХМ3-2"
                        },
                        new
                        {
                            ID = 35,
                            ACoeff = 3.8000000000000001E-07,
                            BCoeff = -0.00101,
                            CCoeff = 2.3199999999999998,
                            MaterialGroupID = 7,
                            Name = "ХМ4-1"
                        },
                        new
                        {
                            ID = 36,
                            ACoeff = 2.3099999999999999E-07,
                            BCoeff = 0.00016799999999999999,
                            CCoeff = 0.045999999999999999,
                            MaterialGroupID = 8,
                            Name = "МКРВ-80"
                        },
                        new
                        {
                            ID = 37,
                            ACoeff = 1.49E-07,
                            BCoeff = 0.000136,
                            CCoeff = 0.047,
                            MaterialGroupID = 9,
                            Name = "МКРР-130"
                        },
                        new
                        {
                            ID = 38,
                            ACoeff = 1.3199999999999999E-07,
                            BCoeff = 0.000122,
                            CCoeff = 0.049000000000000002,
                            MaterialGroupID = 9,
                            Name = "МКРРХ-150"
                        },
                        new
                        {
                            ID = 39,
                            ACoeff = 1.3199999999999999E-07,
                            BCoeff = 0.000122,
                            CCoeff = 0.049000000000000002,
                            MaterialGroupID = 9,
                            Name = "МКЦ-150"
                        },
                        new
                        {
                            ID = 40,
                            ACoeff = 1.06E-07,
                            BCoeff = 9.6000000000000002E-05,
                            CCoeff = 0.055,
                            MaterialGroupID = 10,
                            Name = "МКРВ-200"
                        },
                        new
                        {
                            ID = 41,
                            ACoeff = 7.0000000000000005E-08,
                            BCoeff = 6.8999999999999997E-05,
                            CCoeff = 0.079000000000000001,
                            MaterialGroupID = 11,
                            Name = "МКРП-340"
                        },
                        new
                        {
                            ID = 42,
                            ACoeff = 2E-08,
                            BCoeff = 0.00015899999999999999,
                            CCoeff = 0.126,
                            MaterialGroupID = 12,
                            Name = "МКРП-450"
                        },
                        new
                        {
                            ID = 43,
                            ACoeff = 4.9999999999999998E-08,
                            BCoeff = 6.7999999999999999E-05,
                            CCoeff = 0.108,
                            MaterialGroupID = 13,
                            Name = "МКРБ-500"
                        },
                        new
                        {
                            ID = 44,
                            ACoeff = 4.9999999999999998E-08,
                            BCoeff = 6.7999999999999999E-05,
                            CCoeff = 0.108,
                            MaterialGroupID = 14,
                            Name = "МКРК-500"
                        });
                });

            modelBuilder.Entity("CylindricalPipeHeatLoss.API.Models.DBModels.MaterialGroupDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.HasKey("ID");

                    b.ToTable("MaterialGroups");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Шамотные огнеупоры общего назначения"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Шамоты легковесные"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Корундовые обычные"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Корундовые легковесы"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Магнезитовые (периклазовые)"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Периклазошпинелидные хромитовые"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Хромитопериклазовые"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Вата"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Рулонный материал"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Войлок"
                        },
                        new
                        {
                            ID = 11,
                            Name = "Плиты на органической связке"
                        },
                        new
                        {
                            ID = 12,
                            Name = "Плиты на неорганической связке"
                        },
                        new
                        {
                            ID = 13,
                            Name = "Бумага"
                        },
                        new
                        {
                            ID = 14,
                            Name = "Картон"
                        });
                });

            modelBuilder.Entity("CylindricalPipeHeatLoss.API.Models.DBModels.PipeLayerDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("ReportID");

                    b.ToTable("PipeLayers");
                });

            modelBuilder.Entity("CylindricalPipeHeatLoss.API.Models.DBModels.RadiusDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("ReportID");

                    b.ToTable("Radiuses");
                });

            modelBuilder.Entity("CylindricalPipeHeatLoss.API.Models.DBModels.ReportDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("InnerTemp")
                        .HasColumnType("REAL");

                    b.Property<double>("OutterTemp")
                        .HasColumnType("REAL");

                    b.Property<double>("PipeLength")
                        .HasColumnType("REAL");

                    b.Property<double>("Q")
                        .HasColumnType("REAL");

                    b.Property<double>("a1")
                        .HasColumnType("REAL");

                    b.Property<double>("a2")
                        .HasColumnType("REAL");

                    b.Property<double>("e")
                        .HasColumnType("REAL");

                    b.Property<double>("ql")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("CylindricalPipeHeatLoss.API.Models.DBModels.TemperatureDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("ReportID");

                    b.ToTable("Temperatures");
                });

            modelBuilder.Entity("CylindricalPipeHeatLoss.API.Models.DBModels.MaterialDB", b =>
                {
                    b.HasOne("CylindricalPipeHeatLoss.API.Models.DBModels.MaterialGroupDB", "MaterialGroup")
                        .WithMany("Materials")
                        .HasForeignKey("MaterialGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialGroup");
                });

            modelBuilder.Entity("CylindricalPipeHeatLoss.API.Models.DBModels.PipeLayerDB", b =>
                {
                    b.HasOne("CylindricalPipeHeatLoss.API.Models.DBModels.MaterialDB", "Material")
                        .WithMany("PipeLayers")
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CylindricalPipeHeatLoss.API.Models.DBModels.ReportDB", "Report")
                        .WithMany("PipeLayers")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CylindricalPipeHeatLoss.API.Models.DBModels.RadiusDB", b =>
                {
                    b.HasOne("CylindricalPipeHeatLoss.API.Models.DBModels.ReportDB", "Report")
                        .WithMany("Radiuses")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CylindricalPipeHeatLoss.API.Models.DBModels.TemperatureDB", b =>
                {
                    b.HasOne("CylindricalPipeHeatLoss.API.Models.DBModels.ReportDB", "Report")
                        .WithMany("Temperatures")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("CylindricalPipeHeatLoss.API.Models.DBModels.MaterialDB", b =>
                {
                    b.Navigation("PipeLayers");
                });

            modelBuilder.Entity("CylindricalPipeHeatLoss.API.Models.DBModels.MaterialGroupDB", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("CylindricalPipeHeatLoss.API.Models.DBModels.ReportDB", b =>
                {
                    b.Navigation("PipeLayers");

                    b.Navigation("Radiuses");

                    b.Navigation("Temperatures");
                });
#pragma warning restore 612, 618
        }
    }
}
